"""empty message

Revision ID: 15375b4af043
Revises: 97ee1ac69f8e
Create Date: 2021-06-11 21:52:41.772860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15375b4af043'
down_revision = '97ee1ac69f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website_link')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
