"""empty message

Revision ID: 7034549f42d8
Revises: aa49806ece66
Create Date: 2021-06-13 21:07:41.583303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7034549f42d8'
down_revision = 'aa49806ece66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'status',
               existing_type=sa.VARCHAR(length=280))
    op.alter_column('Venue', 'status',
               existing_type=sa.VARCHAR(length=280))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'status',
               existing_type=sa.VARCHAR(length=120))
    op.alter_column('Artist', 'status',
               existing_type=sa.VARCHAR(length=120))
    # ### end Alembic commands ###
